name: pr open workflow
on:
  pull_request:
    types:
      - opened
jobs:
  pr_raise:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The pr is raised on target branch of ${{github.base_ref}}"
          echo "The pr is raised on base branch of ${{github.head_ref	}}"
          echo "${{	github.ref}}"
          echo "${{github.ref_name}}"
